org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.219
loader_version_range=[1,)

# Mod Info
mod_id=sinomagic
mod_name=SinoMagic
mod_authors=MochaoHorizon
mod_license=MIT license
mod_version=1.0.0
mod_group_id=com.mochaohorizon.sinomagic
mod_description=七月流火，九月授衣，春日载阳，有鸣仓庚

#Dependencies Info
farmersdelight_version=1.2.4a
geckolib_version=4.8.3
