#Sorry, DMHR114514's English is very average, I learn mostly written English. :)
#I should say thanks for simibubi, I learn much on mods.toml of create. qwq
modLoader="javafml"
loaderVersion="[0,)"
license="MIT"

[[mods]]
modId="chmagic"
version="0.1.0"
displayName="ChineseMagic"
authors="agnoeuf_creative_club(ExTetragon and DMHR114514 most)"
logoflie="icon.png"
description="This is a mod that shows the charm of Chinese culture."

[[mixins]]
config="chmagic.mixins.json"

#These are things what chmagic-mod have to use.
#Although Farmer's Delight is the dependencies of chmagic-mod, but chmagic-mod also have many content, at least on the plan. XD
[[dependencies."chmagic"]]
modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies."chmagic"]]
    modId="neoforge"
    type="required"
    versionRange="[21.2.206,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."chmagic"]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.4a,)"
    ordering="NONE"
    side="BOTH"

#This mod need create to realize mechanized food production. But I think that sometimes making food by hand is also a very romantic thing. Yes, I like create too! :D
[[dependencies."chmagic"]]
    modId="create"
    type="optional"
    versionRange="[6.0.1,)"
    ordering="NONE"
    side="BOTH"

#It is impossible to wake them up.
[[dependencies."chmagic"]]
    modId="sakura"
    type="incompatible"
    versionRange="[0.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."chmagic"]]
    modId="chinjufumod"
    type="incompatible"
    versionRange="[0.0.1,)"
    ordering="NONE"
    side="BOTH"