#Sorry, DMHR114514's English is very average, I learn mostly written English. :)
#I should say thanks for simibubi, I learn much on mods.toml of create. qwq
modLoader="javafml"
loaderVersion="[0,)"
license="MIT"

[[mods]]
modId="sinomagic"
version="1.0.0"
displayName="SinoMagic"
displayURL="https://github.com/MochaoHorizon/SinoMagic"
authors="MochaoHorizon"
logoflie="icon.png"
credits="一只带明球(DMHR114514), 荧惑启明(ExTetRagon), 克劳德(Cloud1232534), 之一"
description="七月流火，九月授衣，春日载阳，有鸣仓庚"

[[mixins]]
config="sinomagic.mixins.json"

#These are things what sinomagic have to use.
#Although Farmer's Delight is the dependencies of sinomagic, but sinomagic also have many content, at least on the plan. XD
[[dependencies."sinomagic"]]
modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies."sinomagic"]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.185,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."sinomagic"]]
    modId="farmersdelight"
    type="required"
    versionRange="[1.2.4a,)"
    ordering="NONE"
    side="BOTH"

[[dependencies."sinomagic"]]
    modId="geckolib"
    type="required"
    versionRange="[4.8.3]"
    ordering="NONE"
    side="BOTH"

#This mod need create to realize mechanized food production. But I think that sometimes making food by hand is also a very romantic thing. Yes, I like create too!
[[dependencies."sinomagic"]]
    modId="create"
    type="optional"
    versionRange="[6.0.10,)"
    ordering="NONE"
    side="BOTH"