#Sorry, DMHR114514's English is very average, I learn mostly written English. :)
#I should say thanks for simibubi, I learn much on mods.toml of create. qwq
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Agnoeuf Creative Club(ExTetragon and DMHR114514 most)"
logoflie="icon.png"
description="This is a mod that shows the charm of Chinese culture."

[[mixins]]
config="${mod_id}.mixins.json"

#These are things what chmagic-mod have to use.
#Although Farmer's Delight is the dependencies of chmagic-mod, but chmagic-mod also have many content, at least on the plan. XD
[[dependencies.${mod_id}]]
modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.219,)"
    ordering="NONE"
    side="BOTH"

#[[dependencies.${mod_id}]]
#    modId="farmersdelight"
#    type="required"
#    versionRange="[1.2.4a,)"
#    ordering="NONE"
#    side="BOTH"

#This mod need create to realize mechanized food production. But I think that sometimes making food by hand is also a very romantic thing. Yes, I like create too! :D
#[[dependencies.${mod_id}]]
#    modId="create"
#    type="optional"
#    versionRange="[6.0.1,)"
#    ordering="NONE"
#    side="BOTH"

#It is impossible to wake them up.
#[[dependencies.${mod_id}]]
#    modId="sakura"
#    type="incompatible"
#    versionRange="[0.0.1,)"
#    ordering="NONE"
#    side="BOTH"

#[[dependencies.${mod_id}]]
#    modId="chinjufumod"
#    type="incompatible"
#    versionRange="[0.0.1,)"
#    ordering="NONE"
#    side="BOTH"